# Check PR created by code owner and approve.

name: Auto Approve Code Owner PR
on:
  pull_request:
    branches:
      - main
    types: opened

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - id: checkIsOwner
        name: Check Is Owner
        uses: orkunkarakus/react-native-cross-select/.github/action/isCodeOwner@main
        with:
          USERNAME: ${{ github.event.pull_request.user.login }}

      # Approve PR
      - name: Approve PR
        if: ${{ steps.checkIsOwner.outputs.IS_CODE_OWNER == 'true' }}
        run: gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}